language: c
sudo: required
dist: bionic
env:
  matrix:
    - EMACS=emacs25
    - EMACS=emacs26

branches:
  only:
    - master

install:
  - if [ "$EMACS" = 'emacs26' ]; then
        sudo add-apt-repository -y ppa:kelleyk/emacs &&
        sudo apt-get update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs26 emacs26-el;
    fi

script:
  - $EMACS --version
  - $EMACS --batch --eval "(progn (package-initialize) (package-install 's))"
  - $EMACS --batch -L . --eval "(setq byte-compile-error-on-warn t)" -f batch-byte-compile julia-repl.el
  - $EMACS --batch -L . -l ert -l julia-repl-tests.el -f ert-run-tests-batch-and-exit;

notifications:
  email: false
